export const PLUGIN_NAME = 'ChunkRestrictionPlugin';

export const SEVERITY_TYPES = {
	ERROR: 'error',
	WARNING: 'warning',
	INFO: 'info'
};

export const REASONS = {
	INVALID_ASSET_SIZE: 'INVALID_ASSET_SIZE',
	INVALID_DELTA_SIZE: 'INVALID_DELTA_SIZE',
	EXCEEDS_LIMIT: 'EXCEEDS_LIMIT',
	WARN_ON_DELTA_LIMIT: 'WARN_ON_DELTA_LIMIT',
	WITHIN_LIMIT: 'WITHIN_LIMIT',
	MISSING: 'MISSING'
};
